name: Build
on:
  push:
    paths-ignore:
      - '**.pdf'
      - '**.rst'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - '**.pdf'
      - '**.rst'
      - '.gitignore'


jobs:
  build:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs_version:
          - '26.1'
          - '26.2'
          - '26.3'
          - '27.1'
          - '28.1'
          - '29.4'
          - '30.1'
        cask_version:
          - 'snapshot'
    steps:
      - uses: actions/checkout@v1
        with:
          python-version: '3.9'
          architecture: 'x64'
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run build
        env:
          EMACS_INIT: ${{ github.workspace }}/ci/init.el
        run: make clean all
