name: Build
on:
  push:
    paths-ignore:
      - '**.pdf'
      - '**.rst'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - '**.pdf'
      - '**.rst'
      - '.gitignore'


jobs:
  build:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Ubuntu Linux runs several Emacs versions
          - os: ubuntu-latest
            emacs_version: '26.1'
          - os: ubuntu-latest
            emacs_version: '26.2'
          - os: ubuntu-latest
            emacs_version: '26.3'
          - os: ubuntu-latest
            emacs_version: '27.1'
          - os: ubuntu-latest
            emacs_version: '28.1'
          - os: ubuntu-latest
            emacs_version: '29.4'
          - os: ubuntu-latest
            emacs_version: '30.1'
          - os: macos-latest
            emacs_version: '29.4'
          - os: macos-latest
            emacs_version: '30.1'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run build
        env:
          EMACS_INIT: ${{ github.workspace }}/ci/init.el
        run: make clean all
