# YAML FILE: build.yml
#
# Purpose   : Automated PEL build.
# Created   : Sunday, January 11 2026.
# Author    : Pierre Rouleau <prouleau001@gmail.com>
# Time-stamp: <2026-02-27 10:06:54 EST, updated by Pierre Rouleau>
# ----------------------------------------------------------------------------
# Module Description
# ------------------
#
# Controls Github action controlled build of PEL code.
# The PEL build byte-compiles all code and runs the ERT-driven tests.

# ----------------------------------------------------------------------------
# Dependencies
# ------------
#
# - Github actions
# - Github Action for Emacs: https://github.com/marketplace/actions/set-up-emacs
#   - This uses Nix.  Since Nix does not support Windows, this prevents running
#     the tests under Windows, unfortunately.
#
# Note that costly tests are currently disabled since I'm trying to only use
# what is free from Github.

# ----------------------------------------------------------------------------
# Code
# ----
#
#

name: Build
on:
  push:
    branches:
      - master # Run only on 'push' for the main branch.
    paths-ignore:
      - '**.pdf'
      - '**.rst'
      - '.gitignore'
  pull_request:
    branches:
      - '**' # Run 'pull-request' for all branches.
    paths-ignore:
      - '**.pdf'
      - '**.rst'
      - '.gitignore'


jobs:
  build:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Ubuntu Linux runs several Emacs versions: 26,1 to 30.1
          - os: ubuntu-latest
            emacs_version: '26.1'
          - os: ubuntu-latest
            emacs_version: '26.2'
          - os: ubuntu-latest
            emacs_version: '26.3'
          - os: ubuntu-latest
            emacs_version: '27.1'
          - os: ubuntu-latest
            emacs_version: '28.1'
          - os: ubuntu-latest
            emacs_version: '29.4'
          - os: ubuntu-latest
            emacs_version: '30.1'
          # On macOS, I did not find anything to test on Emacs 26 running on Intel-based macOS
          # So the tests start at Emacs 27.1 running on the only Intel macOS I have found.
          # However, the large costs too much and I am disabling it..
          # I am currently testing Emacs 26.3 on a local image.
          # - os: macos-14-large
          #   emacs_version: '27.1'
          - os: macos-latest
            emacs_version: '28.1'
          - os: macos-latest
            emacs_version: '29.4'
          - os: macos-latest
            emacs_version: '30.1'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run build
        env:
          EMACS_INIT: ${{ github.workspace }}/ci/init.el
        run: make all

# ----------------------------------------------------------------------------
